export const startupIdeas = [
  {
    id: 1,
    title: "EcoDeliver",
    description:
      "Carbon-neutral delivery service using electric bikes and optimized routing AI. Targeting urban areas with same-day delivery for local businesses.",
    founder: "@sarah_chen",
    timestamp: "3 hours ago",
    rating: 8.7,
    ratingCount: 23,
    upvotes: 156,
    downvotes: 12,
    comments: 18,
    views: 1234,
    fundingGoal: 50000,
    category: "Sustainability",
    thumbnail:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop&crop=center",
  },
  {
    id: 2,
    title: "MindfulAI",
    description:
      "AI-powered mental health companion that provides personalized meditation and therapy recommendations based on mood analysis.",
    founder: "@alex_rivera",
    timestamp: "5 hours ago",
    rating: 9.1,
    ratingCount: 45,
    upvotes: 289,
    downvotes: 8,
    comments: 34,
    views: 2156,
    fundingGoal: 75000,
    category: "Health Tech",
    thumbnail:
      "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop&crop=center",
  },
  {
    id: 3,
    title: "CodeMentor",
    description:
      "Platform connecting junior developers with experienced mentors for real-time code reviews and career guidance sessions.",
    founder: "@dev_mike",
    timestamp: "1 day ago",
    rating: 7.8,
    ratingCount: 67,
    upvotes: 198,
    downvotes: 23,
    comments: 52,
    views: 3421,
    fundingGoal: 100000,
    category: "EdTech",
    thumbnail:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400&h=300&fit=crop&crop=center",
  },
  {
    id: 4,
    title: "SmartGarden",
    description:
      "IoT-enabled urban farming solution with automated watering, nutrient monitoring, and crop optimization for small spaces.",
    founder: "@green_thumb",
    timestamp: "2 days ago",
    rating: 8.3,
    ratingCount: 34,
    upvotes: 124,
    downvotes: 15,
    comments: 29,
    views: 987,
    fundingGoal: 40000,
    category: "AgriTech",
    thumbnail:
      "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop&crop=center",
  },
  {
    id: 5,
    title: "VirtualFit",
    description:
      "AR fitness platform that transforms any space into a personal gym with virtual trainers and real-time form correction.",
    founder: "@fitness_guru",
    timestamp: "3 days ago",
    rating: 8.9,
    ratingCount: 78,
    upvotes: 312,
    downvotes: 19,
    comments: 67,
    views: 4532,
    fundingGoal: 200000,
    category: "Fitness Tech",
    thumbnail:
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=300&fit=crop&crop=center",
  },
  {
    id: 6,
    title: "CryptoSafe",
    description:
      "Decentralized password manager with blockchain-based encryption and biometric authentication for ultimate security.",
    founder: "@crypto_dev",
    timestamp: "4 days ago",
    rating: 7.5,
    ratingCount: 91,
    upvotes: 267,
    downvotes: 45,
    comments: 83,
    views: 5643,
    fundingGoal: 150000,
    category: "Security",
    thumbnail:
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=400&h=300&fit=crop&crop=center",
  },
];
